<?php
/**
 * This file contains the code for PHP HTML Object extension gateway
 * 
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * PHP Versions 5
 *
 * @category    PHP Object
 * @package     HTML Object
 * @author      Abdul Hanan (http://hanan.qummatic.com) Original Author
 * @copyright   2011 bekasi-code.qummatic.com
 * @license     http://www.gnu.org/licenses/lgpl-3.0.txt LGPL Version 3
 * @version     ver 0.2
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */

/**
 * HTML Object Extension class
 *
 * @subpackage HTMLObject Extension
 * @access public
 * @version class-ver 0.2
 * @author Abdul Hanan (http://hanan.qummatic.com) Original Author
 */
class HO_Extension extends HTML_Object
{
    /**
     * Constructor of the container class
     *
     * @access public
     */
    public function __construct()
    {
        parent::__construct();
    }
}
?>
