<?php
/**
 * This file contains the code for making table footer elements
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * PHP Versions 5
 *
 * @category    PHP Object
 * @package     HTML Object
 * @author      Abdul Hanan (http://hanan.qummatic.com) Original Author
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://www.gnu.org/licenses/lgpl-3.0.txt LGPL Version 3
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */

/**
 * HTML Table Footer class
 * 
 * This class is used for generating table footer element, its attributes, and
 * its contents.
 *
 * @subpackage HTML Table
 * @access  private
 * @version class-ver 0.1.1
 * @author Abdul Hanan (http://hanan.qummatic.com)
 */
class HO_Table_TFoot extends HO_Table
{
    /**
     * @var     object
     * @access  public
     */
    public $row;

    /**#@+*/
    /**
     * @var     array
     * @access  private
     */
    private $arrRow = array();
    private $arrTFoot = array();
    private $arrAttributes = array();
    private $arrTableTFoot = array();
    /**#@-*/

    /**
     * @var     string
     * @access  private
     */
    private $tableTFoot;

    /**
     * Constructor of the container class
     * 
     * Assigns table footer information into $arrTFoot property
     *
     * @access public
     * @param array $argTFoot
     */
    public function __construct($argTFoot)
    {
        $this->arrTFoot = $argTFoot;
    }

    /**
     * Processes Table Footer
     * 
     * Scripts for processing to create table footer element, its attributes,
     * and its contents
     *
     * @access private
     * @return string
     */
    private function process()
    {
        $tfootContent = "";
        foreach ($this->arrTableTFoot as $value) {
            $tfootContent .= $value;
        }

        $tagTFoot = $this->__tfoot($this->arrTFoot['id']);
        foreach ($this->arrAttributes as $key => $value) {
            $tagTFoot->attribute($key, $value);
        }
        $tagTFoot->innerHTML($tfootContent);
        $this->tableTFoot = $tagTFoot->fetch();
    }

    /**
     * Defines Table Footer Tag Attribute
     * 
     * Assigns an attribute tag for table footer tag (<tfoot>) and its value
     *
     * @access public
     * @param string $argName
     * @param string $argValue
     */
    public function attribute($argName, $argValue)
    {
        $this->arrAttributes[$argName] = $argValue;
    }

    /**
     * Defines STYLE Attribute
     * 
     * Assigns style attribute with its value into table footer element
     *
     * @access public
     * @param string $argStyle
     */
    public function style($argStyle)
    {
        $this->arrAttributes['style'] = $argStyle;
    }

    /**
     * Registers Row of Table Footer Element
     * 
     * Registers row object for making table footer's row
     *
     * @access public
     * @param string $argID
     */
    public function row($argID = NULL)
    {
        if (!is_null($argID) && trim($argID))
            $this->arrRow = array('id'=>$argID);
        else
            $this->arrRow = array('id'=>'table-row');
        
        $this->row = new HO_Table_Row($this->arrRow);
    }

    /**
     * Applies Table Body
     * 
     * Applies row into table footer element
     *
     * @access public
     */
    public function apply()
    {
        $this->arrTableTFoot[] = $this->row->fetch();

        unset($this->row);
    }

    /**
     * Fetches Table Body
     * 
     * Returns table footer, its attribute and its contents
     *
     * @access public
     * @return string
     */
    public function fetch()
    {
        $this->process();

        return $this->tableTFoot;
    }

    /**
     * Displays Table Footer
     *
     * @access public
     */
    public function display()
    {
        echo $this->fetch();
    }
}
?>
