<?php
/**
 * This file contains the code for making table row elemets
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * PHP Versions 5
 *
 * @category    PHP Object
 * @package     HTML Object
 * @author      Abdul Hanan (http://hanan.qummatic.com) Original Author
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://www.gnu.org/licenses/lgpl-3.0.txt LGPL Version 3
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */

/**
 * HTML Table Row Class
 * 
 * This class is used for generating Table Row element, its attributes,
 * and its contents.
 *
 * @subpackage HTML Table
 * @access  private
 * @version class-ver 0.1.1
 * @author Abdul Hanan (http://hanan.qummatic.com)
 */
class HO_Table_Row extends HO_Table
{
    /**#@+*/
    /**
     * @var     array
     * @access  private
     */
    private $arrRow = array();
    private $arrAttributes = array();
    private $arrCols = array();
    /**#@-*/
    
    /**
     * @var     string
     * @access  private
     */
    private $tableRow;


    /**
     * Constructor of the container class
     * 
     * Assigns table row information into $arrRow variable
     *
     * @access public
     * @param string $argRow
     */
    public function __construct($argRow)
    {
        $this->arrRow = $argRow;
    }

    /**
     * Processes Table Row
     * 
     * Scripts to processing to create Table Row element, its attributes, and its contents
     *
     * @access private
     */
    private function process()
    {
        $rowContent = "";
        foreach ($this->arrCols as $value) {
            $rowContent .= $value;
        }

        $tagRow = $this->__tr($this->arrRow['id']);
        foreach ($this->arrAttributes as $key => $value) {
            $tagRow->attribute($key, $value);
        }
        $tagRow->innerHTML($rowContent);
        $this->tableRow = $tagRow->fetch();
    }

    /**
     * Defines Row Tag Attribute
     * 
     * Assigns a tag attribute and its value
     *
     * @access public
     * @param string $argName
     * @param string $argValue
     */
    public function attribute($argName, $argValue = NULL)
    {
        $this->arrAttributes[$argName] = $argValue;
    }

    /**
     * Defines STYLE Attribute
     * 
     * Assigns style attribute with its value into table row element
     *
     * @access public
     * @param string $argStyle
     */
    public function style($argStyle)
    {
        $this->arrAttributes['style'] = $argStyle;
    }

    /**
     * Registers Table Column
     * 
     * Registers table column object for making column element, its attributes
     * and its contents
     *
     * @access public
     * @param string $argContent
     * @param array $argAttributes
     */
    public function col($argContent, $argAttributes = array())
    {
        $tagTD = $this->__td();
        $tagTD->innerHTML($argContent);
        foreach ($argAttributes as $key => $value) {
            $tagTD->attribute($key, $value);
        }
        $this->arrCols[] = $tagTD->fetch();
    }

    /**
     * Registers Table Header Column
     * 
     * Registers table header column object for making head column element,
     * its attributes and its contents
     *
     * @access public
     * @param string $argContent
     * @param array $argAttributes
     */
    public function head($argContent, $argAttributes = array())
    {
        $tagTH = $this->__th();
        $tagTH->innerHTML($argContent);
        foreach ($argAttributes as $key => $value) {
            $tagTH->attribute($key, $value);
        }
        $this->arrCols[] = $tagTH->fetch();
    }

    /**
     * Fetches Table Row
     * 
     * Returns table row element, its attributes and its contents
     * 
     * @access public
     * @return string
     */
    public function fetch()
    {
        $this->process();

        return $this->tableRow;
    }

    /**
     * Displays Table Row
     * 
     * Displays table row element, its attributes and its contents
     *
     * @access public
     */
    public function display()
    {
        echo $this->fetch();
    }
}
?>
