<?php
/**
 * This file contains the sample of PHP HTML Object
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * @author      Abdul Hanan (http://hanan.qummatic.com)
 * @copyright   2011 bekasi-code.qummatic.com
 * @license     http://creativecommons.org/licenses/GPL/2.0/ CC-GNU GPL version 2 or later
 * @version     ver 0.2-dev
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */

// Requires HTML Object Class Library
require "../libs/HTML_Object.php";

// Defines HTML_Object() Class
$objHTML = new HTML_Object();

// Assigns $body variable that contains HTML Tags is generated by HTML Object
$body = $objHTML->header("Welcome to Sample Document", 1);
$body .= $objHTML->page("This is HTML Document object. You can create HTML document completely over PHP with HTML Object Class Library");
$body = $objHTML->div($body, "content");

// Scripts for creating HTML Document

$objHTMLDocument = clone $objHTML->Document;
$objHTMLDocument->head()
				->title("HTML Object Sample - Document")
				->cssURL("includes/page.css")
				->js('alert("OK!")')
				->jsURL("includes/page.js");
$objHTMLDocument->body()
				->content($body);
$objHTMLDocument->display();
?>
