<?php
/**
 * This file contains the sample of PHP HTML Object
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * @author      Abdul Hanan (http://hanan.qummatic.com)
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://creativecommons.org/licenses/GPL/2.0/ CC-GNU GPL version 2 or later
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */
?>
<html>
<head>
    <title>HTML Object Sample - HTML Tag !!!</title>
    <link rel="stylesheet" type="text/css" href="includes/tags.css" />
</head>
<body>
    <pre>
<?php
    if (isset($_GET['submit']) && $_GET['submit']) {
        echo "Submitted information: ";
        print_r($_POST);
    }
?>
    </pre>
<?php
// Requires HTML Object Class Library
require "../libs/HTML_Object.php";

// Defines HTML_Object() Class
$htmlObject = new HTML_Object();
echo $htmlObject->header('Samples of HTML Form Object');

$content .= $htmlObject->page('Full name: ' . $htmlObject->Form->input('fullname', 'text', '', 'fullname'));
$content .= $htmlObject->page('City: ' . $htmlObject->Form->select('city', array('JKT'=>'Jakarta', 'BDG'=>'Bandung', 'SMG'=>'Semarang'), 'city'));
$content .= $htmlObject->page('Your note: ' . $htmlObject->Form->textarea('note', '', 'note', array('cols'=>25, 'rows'=>7)));
$content .= $htmlObject->page($htmlObject->Form->input('submit', 'submit', 'Submit', NULL, array('class'=>'button')));
echo $htmlObject->Form->form($content, 'form_sample', 'form_sample', 'form.php?submit=1', 'post');
?>

</body>
</html>
