<?php
/**
 * This file contains the sample of PHP HTML Object
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * @author      Abdul Hanan (http://hanan.qummatic.com)
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://creativecommons.org/licenses/GPL/2.0/ CC-GNU GPL version 2 or later
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */
?>
<html>
<head>
    <title>HTML Object Sample - Hello !!!</title>
</head>
<body>
<?php
// Requires HTML Object Class Library
require "../libs/HTML_Object.php";

// Defines HTML_Object() Class
$objHTML = new HTML_Object();

// Output: <div style="font-weight:bold;">Hello !!!</div>
echo $objHTML->div("Hello !!!", NULL, "font-weight:bold;");
?>
</body>
</html>
