<?php
/**
 * This file contains the sample of PHP HTML Object
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * @author      Abdul Hanan (http://hanan.qummatic.com)
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://creativecommons.org/licenses/GPL/2.0/ CC-GNU GPL version 2 or later
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */
?>
<html>
<head>
    <title>HTML Object Sample - List</title>
    <link rel="stylesheet" type="text/css" href="includes/tags.css" />
</head>
<body>
<?php
require "../libs/HTML_Object.php";

// Defines HTML_Object() Class
$objHTML = new HTML_Object();

echo $objHTML->header('Samples of Bullet and Numbering');

// {{{ bullet list samples
// simple list
$lists = array('List 1', 'List 2', 'List 3');
echo $objHTML->bullet($lists, 'ul-sample-1');

// with <li> id-attribute
$lists = array(
            array('List 1', 'list-1'),
            array('List 2', 'list-2'),  
            array('List 3', 'list-3'));
echo $objHTML->bullet($lists, 'ul-sample-2');

// with <li> other attributes
$lists = array(
            array('List 1', 'list-1', array('style'=>'font-weight: bold;')),
            array('List 2', 'list-2', array('style'=>'font-style: italic;')),  
            array('List 3', 'list-3', array('class'=>'sample-list-3')));
echo $objHTML->bullet($lists, 'ul-sample-2');
// }}}

// {{{ numbering list samples
// simple list
$lists = array('List 1', 'List 2', 'List 3');
echo $objHTML->numbering($lists, 'ol-sample');

// with <li> id-attribute
$lists = array(
            array('List 1', 'list-1'),
            array('List 2', 'list-2'),  
            array('List 3', 'list-3'));
echo $objHTML->numbering($lists, 'ul-sample-2');

// with <li> other attributes
$lists = array(
            array('List 1', 'list-1', array('style'=>'font-weight: bold;')),
            array('List 2', 'list-2', array('style'=>'font-style: italic;')),  
            array('List 3', 'list-3', array('class'=>'sample-list-3')));
echo $objHTML->numbering($lists, 'ul-sample-2');
// }}}
?>
</body>
</html>
