<?php
/**
 * This file contains the sample of PHP HTML Object
 *
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * @author      Abdul Hanan (http://hanan.qummatic.com)
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://creativecommons.org/licenses/GPL/2.0/ CC-GNU GPL version 2 or later
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */
?>
<html>
<head>
    <title>HTML Object Sample - HTML Tag !!!</title>
    <link rel="stylesheet" type="text/css" href="includes/tags.css" />
</head>
<body>
<?php
// Requires HTML Object Class Library
require "../libs/HTML_Object.php";

// Defines HTML_Object() Class
$objHTML = new HTML_Object();

// Creating <input> tag, with TYPE attribute value is text
$tagInput = $objHTML->__input('text1');
$tagInput->name('text1')
		->attribute('type', 'text')
		->attribute('value', 'Text 1')
		->attribute('size', '25')
		->display();

// Creating <input> tag, with TYPE attribute value is button
$tagInput = $objHTML->__input();
$tagInput->name('button');
$tagInput->setClass('button');
$tagInput->attribute('type', 'button');
$tagInput->attribute('value', 'Click');
$tagInput->display();

echo $objHTML->newline();

// Creating <select> and <option> tag
$tagOption = $objHTML->__option();
$tagOption->attribute('value', 'Yahoo.com');
$tagOption->innerHTML('Yahoo');
$option = $tagOption->fetch();

$tagOption = $objHTML->__option();
$tagOption->attribute('value', 'google.com');
$tagOption->innerHTML('Google');
$option .= $tagOption->fetch();

$tagInput = $objHTML->__select('select1');
$tagInput->innerHTML($option);
echo 'Please select: '.$tagInput->fetch();
?>
</body>
</html>
