<?php
/**
 * This file contains the code for initializing HTML Object library
 * 
 * PHP HTML Object is PHP Object Library for making autogenerated HTML code
 * over PHP Programming. Providing the variety of needs to make HTML code
 * automatically, such as HTML Tags, Attributes, Tag's Content, Frequently Used Tags,
 * and Other HTML Object.
 *
 * PHP Versions 5
 *
 * @author      Abdul Hanan (http://hanan.qummatic.com) Original Author
 * @copyright   2010 bekasi-code.qummatic.com
 * @license     http://www.gnu.org/licenses/lgpl-3.0.txt LGPL Version 3
 * @version     ver 0.1
 * @link        http://bekasi-code.qummatic.com/html-object
 *
 */

define("_LIBS_HTML_OBJECT_", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'HTML_Object');
define("_LIBS_HTML_OBJECT_EXTENSION_", dirname(__FILE__) . DIRECTORY_SEPARATOR . 'extension');
define("_IS_HO_INIT_", 1);

// {{{ main HTML Object libraries
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HTML_Object.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Tag.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Document.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Document_Head.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Document_Body.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Table.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Table_THead.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Table_TBody.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Table_TFoot.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Table_Row.php";
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Form.php";
// }}}

// {{{ extensions
require _LIBS_HTML_OBJECT_ . DIRECTORY_SEPARATOR . "HO_Extension.php";
require dirname(__FILE__) . DIRECTORY_SEPARATOR . "extension.php";
// }}}
?>
